name: flutter_tutorial_chain
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+2
  firebase_auth: ^0.11.1+7
  google_sign_in: ^4.0.1+1
  flutter_facebook_login: ^1.1.1
  flutter_redux: ^0.5.3
  redux: ^3.0.0
  shared_preferences: ^0.4.3
  redux_logging: ^0.3.0
  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  toast: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/collaboration.png
    - images/ic_forward.png
